### ISSUE TITLE
can´t change "the environment variable TS3SERVER_LICENSE to "accept""

### ISSUE THREAD

**Issue by Trancep0rt** [andreasheil/docker-teamspeak3#10]
Greetings!
my ts inside this container seems to had an update. After that, every docker start is stopped after 1 sec with 

> Please set the environment variable TS3SERVER_LICENSE to "accept" in order to accept the license agreement.

"docker start" has no -e option available and i can´t exec the container because it´s not running longer than one second.
Kind regards from germany

**Comment by andreasheil** [comment]
Just use `docker run` instead of `docker start`.
Alternativly create a file named `.ts3server_license_accepted` in the data directory.
