### ISSUE TITLE
Reset Serveradmin Password

### ISSUE THREAD

**Issue by Reedats** [andreasheil/docker-teamspeak3#11]
Hello, I would like to get more information about the administrator password restart (adminkey). 
When i want to set key admin i have to use the command docker run -d -e SERVERADMIN_PASSWORD­=topsecret ... --name=ts3-server ..." while the first time the container is started. **Could be possibly change the token in an existing container?  How can i do IT?** 
Regards

**Comment by andreasheil** [comment]
- delete container
- recreate it while using the `-e SERVERADMIN_PASSWORD`-thing
- next time recreate the container as usual

If the above does not make any sense to you, because you would loose your data during recreation, please (re)read https://docs.docker.com/storage/volumes/

:wink:
