### ISSUE TITLE
Failed to download revocation list

### ISSUE THREAD

**Issue by Andrioshe** [andreasheil/docker-teamspeak3#13]
> poc_1       | 2019-03-01 15:55:16.092079|ERROR   |              |   |TS3ANetwork::ResolveHostName failed error: 
> -3 (Temporary failure in name resolution) 11
> poc_1       | 2019-03-01 15:55:16.092205|ERROR   |              |   |Could not open default UDP connection for weblist

Actually I already opened port 2010/udp and also tried once with deactivated firewall.. nothing changes.

**Comment by andreasheil** [comment]
Hi, please use the official Teamspeak docker image (maybe in combination with watchtower).
This image/repository won't get any updates.
