### ISSUE TITLE
File Transfer fails on second ts3 server

### ISSUE THREAD

**Issue by Andrioshe** [andreasheil/docker-teamspeak3#6]
Hello,
I actually have installed 2 Teamspeak3 Servers. Both are using your docker image and it works fine!

I only got a problem with the second Teamspeak3 Server because the file transfer doesn't work at all.

1. Server
Ports: 9987, 10011, 30033

2. Server
Ports: 9988, 10012, 30034

I already double checked the firewall for the ports but it should be correct.

**Comment by csabike2** [comment]
Hello,
Are you enabled file transfer?
First, right click on you server, and 'Edit virtual server', then click on the transfer tab, and check the settings.
Second, go to Server Groups, and check file transfer permissions.
And third, check the folder permission for file transfer.

I hope it will works after these steps.

**Comment by Andrioshe** [comment]
1. Server Settings for Upload/Download on "-1"
2. Every Servergroup got the permission
3. 1000:1000

The error message I found is "(lost file transfer connection)" but I cant tell how to fix it. The most fixes I found are not helping at all.

**Comment by andreasheil** [comment]
for now there is only this fix for your problem:
1. change the ports in the `ts2server.ini`:
```
filetransfer_port=30034
query_port=10012
```

2. then run the container using the options below:
```
-p 9988:9987/udp \
-p 10012:10012 \
-p 30034:30034 \
```

(don't change the 9987/udp!)

**Comment by Andrioshe** [comment]
worked like a charm! Thanks
